// apps/svelte/src/lib/components/PlaceholderWidget.svelte
<script>
  import { onMount } from 'svelte';
  import { widgetRefreshCounter } from '../stores/appStore.js';
  
  export let id;
  
  const colors = ['#ff6b6b', '#4ecdc4', '#45b7d1', '#f9ca24', '#f0932b', '#eb4d4b', '#6c5ce7', '#a29bfe'];
  const color = colors[id % colors.length];
  
  let number = Math.floor(Math.random() * 1000);
  
  function updateNumber() {
    number = Math.floor(Math.random() * 1000);
  }
  
  $: $widgetRefreshCounter, updateNumber();
</script>

<div class="widget" data-id={id} style="border-top: 4px solid {color}">
  <h3>Widget {id}</h3>
  <div style="font-size: 32px; font-weight: bold; color: {color}">
    {number}
  </div>
</div>

// apps/react/src/components/PlaceholderWidget.jsx
import { useState, useEffect } from 'react';
import { useApp } from '../context/AppContext';

const PlaceholderWidget = ({ id }) => {
  const { widgetRefreshCounter } = useApp();
  const [number, setNumber] = useState(Math.floor(Math.random() * 1000));
  const [color] = useState(() => {
    const colors = ['#ff6b6b', '#4ecdc4', '#45b7d1', '#f9ca24', '#f0932b', '#eb4d4b', '#6c5ce7', '#a29bfe'];
    return colors[id % colors.length];
  });

  useEffect(() => {
    setNumber(Math.floor(Math.random() * 1000));
  }, [widgetRefreshCounter]);

  return (
    <div className="widget" data-id={id} style={{ borderTop: `4px solid ${color}` }}>
      <h3>Widget {id}</h3>
      <div style={{ fontSize: '32px', fontWeight: 'bold', color }}>
        {number}
      </div>
    </div>
  );
};

export default PlaceholderWidget;
