// apps/vue/src/views/About.vue
<template>
  <div class="page">
    <div class="about-page">
      <h1>About</h1>
      <p>
        This application is part of a research study on energy consumption comparison
        of modern JavaScript frameworks: React, Vue, Angular, and Svelte.
      </p>
      <h2>Research Objectives</h2>
      <ul>
        <li>Measure energy consumption across different frameworks</li>
        <li>Analyze performance metrics (render time, memory usage, DOM mutations)</li>
        <li>Compare framework efficiency at different workload scales</li>
        <li>Provide empirical data for green computing practices</li>
      </ul>
      <h2>Methodology</h2>
      <p>
        The study uses RAPL-compatible tools (Scaphandre, Joulemeter, or external power meters)
        to collect energy measurements. Test applications are built identically across all frameworks
        to ensure fair comparison.
      </p>
    </div>
  </div>
</template>

<script>
export default {
  name: 'About'
}
</script>

// apps/react/src/pages/About.jsx
const About = () => {
  return (
    <div className="page">
      <div className="about-page">
        <h1>About</h1>
        <p>
          This application is part of a research study on energy consumption comparison
          of modern JavaScript frameworks: React, Vue, Angular, and Svelte.
        </p>
        <h2>Research Objectives</h2>
        <ul>
          <li>Measure energy consumption across different frameworks</li>
          <li>Analyze performance metrics (render time, memory usage, DOM mutations)</li>
          <li>Compare framework efficiency at different workload scales</li>
          <li>Provide empirical data for green computing practices</li>
        </ul>
        <h2>Methodology</h2>
        <p>
          The study uses RAPL-compatible tools (Scaphandre, Joulemeter, or external power meters)
          to collect energy measurements. Test applications are built identically across all frameworks
          to ensure fair comparison.
        </p>
      </div>
    </div>
  );
};

export default About;
