// apps/react/src/pages/Contact.jsx
import { useState } from 'react';

const Contact = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    message: ''
  });
  const [errors, setErrors] = useState({});
  const [submitted, setSubmitted] = useState(false);

  const validate = () => {
    const newErrors = {};

    if (!formData.name.trim()) {
      newErrors.name = 'Name is required';
    }

    if (!formData.email.trim()) {
      newErrors.email = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'Email is invalid';
    }

    if (!formData.message.trim()) {
      newErrors.message = 'Message is required';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    // Clear error when user starts typing
    if (errors[name]) {
      setErrors(prev => ({ ...prev, [name]: '' }));
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (validate()) {
      // Simulate form submission
      console.log('Form submitted:', formData);
      setSubmitted(true);
      setFormData({ name: '', email: '', message: '' });
      setTimeout(() => setSubmitted(false), 5000);
    }
  };

  return (
    <div className="page">
      <div className="contact-page">
        <h1>Contact</h1>
        <form className="contact-form" onSubmit={handleSubmit}>
          <div>
            <input
              type="text"
              name="name"
              placeholder="Your Name"
              value={formData.name}
              onChange={handleChange}
              className={errors.name ? 'error' : ''}
            />
            {errors.name && <div className="error-message">{errors.name}</div>}
          </div>

          <div>
            <input
              type="email"
              name="email"
              placeholder="Your Email"
              value={formData.email}
              onChange={handleChange}
              className={errors.email ? 'error' : ''}
            />
            {errors.email && <div className="error-message">{errors.email}</div>}
          </div>

          <div>
            <textarea
              name="message"
              placeholder="Your Message"
              rows="5"
              value={formData.message}
              onChange={handleChange}
              className={errors.message ? 'error' : ''}
            />
            {errors.message && <div className="error-message">{errors.message}</div>}
          </div>

          <button type="submit">Send Message</button>
          {submitted && <div className="success-message">Message sent successfully!</div>}
        </form>
      </div>
    </div>
  );
};

export default Contact;

// apps/svelte/src/routes/contact/+page.svelte
<script>
  let formData = {
    name: '',
    email: '',
    message: ''
  };
  
  let errors = {};
  let submitted = false;
  
  function validate() {
    errors = {};
    
    if (!formData.name.trim()) {
      errors.name = 'Name is required';
    }
    
    if (!formData.email.trim()) {
      errors.email = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      errors.email = 'Email is invalid';
    }
    
    if (!formData.message.trim()) {
      errors.message = 'Message is required';
    }
    
    return Object.keys(errors).length === 0;
  }
  
  function handleSubmit() {
    if (validate()) {
      console.log('Form submitted:', formData);
      submitted = true;
      formData = { name: '', email: '', message: '' };
      setTimeout(() => {
        submitted = false;
      }, 5000);
    }
  }
</script>

<div class="page">
  <div class="contact-page">
    <h1>Contact</h1>
    <form class="contact-form" on:submit|preventDefault={handleSubmit}>
      <div>
        <input
          type="text"
          name="name"
          placeholder="Your Name"
          bind:value={formData.name}
          class:error={errors.name}
        />
        {#if errors.name}
          <div class="error-message">{errors.name}</div>
        {/if}
      </div>

      <div>
        <input
          type="email"
          name="email"
          placeholder="Your Email"
          bind:value={formData.email}
          class:error={errors.email}
        />
        {#if errors.email}
          <div class="error-message">{errors.email}</div>
        {/if}
      </div>

      <div>
        <textarea
          name="message"
          placeholder="Your Message"
          rows="5"
          bind:value={formData.message}
          class:error={errors.message}
        />
        {#if errors.message}
          <div class="error-message">{errors.message}</div>
        {/if}
      </div>

      <button type="submit">Send Message</button>
      {#if submitted}
        <div class="success-message">Message sent successfully!</div>
      {/if}
    </form>
  </div>
</div>
