// apps/angular/src/app/pages/contact/contact.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.css']
})
export class ContactComponent {
  formData = {
    name: '',
    email: '',
    message: ''
  };

  errors: { [key: string]: string } = {};
  submitted = false;

  validate(): boolean {
    this.errors = {};

    if (!this.formData.name.trim()) {
      this.errors['name'] = 'Name is required';
    }

    if (!this.formData.email.trim()) {
      this.errors['email'] = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(this.formData.email)) {
      this.errors['email'] = 'Email is invalid';
    }

    if (!this.formData.message.trim()) {
      this.errors['message'] = 'Message is required';
    }

    return Object.keys(this.errors).length === 0;
  }

  handleSubmit(): void {
    if (this.validate()) {
      console.log('Form submitted:', this.formData);
      this.submitted = true;
      this.formData = { name: '', email: '', message: '' };
      setTimeout(() => {
        this.submitted = false;
      }, 5000);
    }
  }
}

<div class="page">
  <div class="contact-page">
    <h1>Contact</h1>
    <form class="contact-form" (ngSubmit)="handleSubmit()" #contactForm="ngForm">
      <div>
        <input
          type="text"
          name="name"
          placeholder="Your Name"
          [(ngModel)]="formData.name"
          [class.error]="errors['name'] && contactForm.submitted"
        />
        <div *ngIf="errors['name'] && contactForm.submitted" class="error-message">
          {{ errors['name'] }}
        </div>
      </div>

      <div>
        <input
          type="email"
          name="email"
          placeholder="Your Email"
          [(ngModel)]="formData.email"
          [class.error]="errors['email'] && contactForm.submitted"
        />
        <div *ngIf="errors['email'] && contactForm.submitted" class="error-message">
          {{ errors['email'] }}
        </div>
      </div>

      <div>
        <textarea
          name="message"
          placeholder="Your Message"
          rows="5"
          [(ngModel)]="formData.message"
          [class.error]="errors['message'] && contactForm.submitted"
        ></textarea>
        <div *ngIf="errors['message'] && contactForm.submitted" class="error-message">
          {{ errors['message'] }}
        </div>
      </div>

      <button type="submit">Send Message</button>
      <div *ngIf="submitted" class="success-message">
        Message sent successfully!
      </div>
    </form>
  </div>
</div>

// apps/svelte/src/routes/contact/+page.svelte
<script>
  let formData = {
    name: '',
    email: '',
    message: ''
  };
  
  let errors = {};
  let submitted = false;
  
  function validate() {
    errors = {};
    
    if (!formData.name.trim()) {
      errors.name = 'Name is required';
    }
    
    if (!formData.email.trim()) {
      errors.email = 'Email is required';
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      errors.email = 'Email is invalid';
    }
    
    if (!formData.message.trim()) {
      errors.message = 'Message is required';
    }
    
    return Object.keys(errors).length === 0;
  }
  
  function handleSubmit() {
    if (validate()) {
      console.log('Form submitted:', formData);
      submitted = true;
      formData = { name: '', email: '', message: '' };
      setTimeout(() => {
        submitted = false;
      }, 5000);
    }
  }
</script>

<div class="page">
  <div class="contact-page">
    <h1>Contact</h1>
    <form class="contact-form" on:submit|preventDefault={handleSubmit}>
      <div>
        <input
          type="text"
          name="name"
          placeholder="Your Name"
          bind:value={formData.name}
          class:error={errors.name}
        />
        {#if errors.name}
          <div class="error-message">{errors.name}</div>
        {/if}
      </div>

      <div>
        <input
          type="email"
          name="email"
          placeholder="Your Email"
          bind:value={formData.email}
          class:error={errors.email}
        />
        {#if errors.email}
          <div class="error-message">{errors.email}</div>
        {/if}
      </div>

      <div>
        <textarea
          name="message"
          placeholder="Your Message"
          rows="5"
          bind:value={formData.message}
          class:error={errors.message}
        />
        {#if errors.message}
          <div class="error-message">{errors.message}</div>
        {/if}
      </div>

      <button type="submit">Send Message</button>
      {#if submitted}
        <div class="success-message">Message sent successfully!</div>
      {/if}
    </form>
  </div>
</div>
