// apps/vue/src/views/Dashboard.vue
<template>
  <div class="page">
    <StatsPanel :item-count="items.length" />
    
    <div class="controls">
      <button id="refresh-widgets" @click="handleRefreshWidgets">
        Refresh Widgets
      </button>
    </div>

    <div class="dashboard" id="widget-grid">
      <WeatherWidget />
      <PlaceholderWidget 
        v-for="i in 24" 
        :key="i + 1" 
        :id="i + 1" 
      />
    </div>

    <ItemList 
      :items="items" 
      @add-items="handleAddItems"
      @remove-items="handleRemoveItems"
    />
  </div>
</template>

<script>
import { ref, onMounted } from 'vue'
import { store } from '../store'
import StatsPanel from '../components/StatsPanel.vue'
import ItemList from '../components/ItemList.vue'
import WeatherWidget from '../components/WeatherWidget.vue'
import PlaceholderWidget from '../components/PlaceholderWidget.vue'

export default {
  name: 'Dashboard',
  components: {
    StatsPanel,
    ItemList,
    WeatherWidget,
    PlaceholderWidget
  },
  setup() {
    const items = ref([])

    onMounted(() => {
      store.incrementPageLoads()
    })

    const handleAddItems = (amount) => {
      const newItems = Array.from({ length: amount }, (_, i) => ({
        id: Date.now() + i,
        name: `Item ${items.value.length + i + 1}`
      }))
      items.value.push(...newItems)
      store.incrementItemCounter(amount)
    }

    const handleRemoveItems = (amount) => {
      const removed = items.value.splice(0, amount)
      store.decrementItemCounter(removed.length)
    }

    const handleRefreshWidgets = () => {
      store.refreshWidgets()
    }

    return {
      items,
      handleAddItems,
      handleRemoveItems,
      handleRefreshWidgets
    }
  }
}
</script>

// apps/angular/src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { AppService } from '../../app.service';
import { Item } from '../../components/item-list/item-list.component';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  items: Item[] = [];
  widgetIds = Array.from({ length: 24 }, (_, i) => i + 2);

  constructor(private appService: AppService) {}

  ngOnInit(): void {
    this.appService.incrementPageLoads();
  }

  handleAddItems(amount: number): void {
    const newItems: Item[] = Array.from({ length: amount }, (_, i) => ({
      id: Date.now() + i,
      name: `Item ${this.items.length + i + 1}`
    }));
    this.items.push(...newItems);
    this.appService.incrementItemCounter(amount);
  }

  handleRemoveItems(amount: number): void {
    const removed = this.items.splice(0, amount);
    this.appService.decrementItemCounter(removed.length);
  }

  handleRefreshWidgets(): void {
    this.appService.refreshWidgets();
  }
}

<div class="page">
  <app-stats-panel [itemCount]="items.length"></app-stats-panel>
  
  <div class="controls">
    <button id="refresh-widgets" (click)="handleRefreshWidgets()">
      Refresh Widgets
    </button>
  </div>

  <div class="dashboard" id="widget-grid">
    <app-weather-widget></app-weather-widget>
    <app-placeholder-widget
      *ngFor="let id of widgetIds"
      [id]="id"
    ></app-placeholder-widget>
  </div>

  <app-item-list
    [items]="items"
    (addItems)="handleAddItems($event)"
    (removeItems)="handleRemoveItems($event)"
  ></app-item-list>
</div>
