// apps/react/src/components/ItemList.jsx
import { useState, useMemo } from 'react';

const ItemList = ({ items, onAddItems, onRemoveItems }) => {
  const [filterQuery, setFilterQuery] = useState('');
  const [sortBy, setSortBy] = useState('id'); // 'id' or 'name'
  const [addAmount, setAddAmount] = useState(100);

  const filteredAndSortedItems = useMemo(() => {
    let result = items;

    // Filter
    if (filterQuery) {
      result = result.filter(item =>
        item.name.toLowerCase().includes(filterQuery.toLowerCase())
      );
    }

    // Sort
    result = [...result].sort((a, b) => {
      if (sortBy === 'name') {
        return a.name.localeCompare(b.name);
      }
      return a.id - b.id;
    });

    return result;
  }, [items, filterQuery, sortBy]);

  const handleAdd = () => {
    onAddItems(addAmount);
  };

  const handleRemove = () => {
    onRemoveItems(50);
  };

  const handleFilter = () => {
    setFilterQuery(filterQuery === 'item' ? '' : 'item');
  };

  const handleSort = () => {
    setSortBy(sortBy === 'id' ? 'name' : 'id');
  };

  return (
    <div>
      <div className="controls">
        <input
          id="item-input"
          type="number"
          value={addAmount}
          onChange={(e) => setAddAmount(parseInt(e.target.value) || 100)}
          min="10"
          max="500"
        />
        <button id="add-btn" onClick={handleAdd}>
          Add {addAmount} Items
        </button>
        <button id="remove-btn" onClick={handleRemove}>
          Remove 50 Items
        </button>
        <button id="filter-btn" onClick={handleFilter}>
          {filterQuery ? 'Clear Filter' : 'Filter "Item"'}
        </button>
        <button id="sort-btn" onClick={handleSort}>
          Sort by {sortBy === 'id' ? 'Name' : 'ID'}
        </button>
      </div>

      <div className="item-list">
        <h3>
          Dynamic Items (<span id="list-count">{filteredAndSortedItems.length}</span>)
        </h3>
        <ul id="item-list">
          {filteredAndSortedItems.map((item) => (
            <li key={item.id} className="item">
              <span>ID: {item.id}</span>
              <span>{item.name}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

export default ItemList;

// apps/vue/src/components/ItemList.vue
<template>
  <div>
    <div class="controls">
      <input
        id="item-input"
        type="number"
        v-model.number="addAmount"
        min="10"
        max="500"
      />
      <button id="add-btn" @click="handleAdd">Add {{ addAmount }} Items</button>
      <button id="remove-btn" @click="handleRemove">Remove 50 Items</button>
      <button id="filter-btn" @click="handleFilter">
        {{ filterQuery ? 'Clear Filter' : 'Filter "Item"' }}
      </button>
      <button id="sort-btn" @click="handleSort">
        Sort by {{ sortBy === 'id' ? 'Name' : 'ID' }}
      </button>
    </div>

    <div class="item-list">
      <h3>
        Dynamic Items (<span id="list-count">{{ filteredAndSortedItems.length }}</span>)
      </h3>
      <ul id="item-list">
        <li v-for="item in filteredAndSortedItems" :key="item.id" class="item">
          <span>ID: {{ item.id }}</span>
          <span>{{ item.name }}</span>
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
import { ref, computed } from 'vue'

export default {
  name: 'ItemList',
  props: {
    items: {
      type: Array,
      default: () => []
    }
  },
  emits: ['add-items', 'remove-items'],
  setup(props, { emit }) {
    const filterQuery = ref('')
    const sortBy = ref('id')
    const addAmount = ref(100)

    const filteredAndSortedItems = computed(() => {
      let result = [...props.items]

      if (filterQuery.value) {
        result = result.filter(item =>
          item.name.toLowerCase().includes(filterQuery.value.toLowerCase())
        )
      }

      if (sortBy.value === 'name') {
        result.sort((a, b) => a.name.localeCompare(b.name))
      } else {
        result.sort((a, b) => a.id - b.id)
      }

      return result
    })

    const handleAdd = () => {
      emit('add-items', addAmount.value)
    }

    const handleRemove = () => {
      emit('remove-items', 50)
    }

    const handleFilter = () => {
      filterQuery.value = filterQuery.value === 'item' ? '' : 'item'
    }

    const handleSort = () => {
      sortBy.value = sortBy.value === 'id' ? 'name' : 'id'
    }

    return {
      filterQuery,
      sortBy,
      addAmount,
      filteredAndSortedItems,
      handleAdd,
      handleRemove,
      handleFilter,
      handleSort
    }
  }
}
</script>
