// apps/react/src/components/StatsPanel.jsx
import { useApp } from '../context/AppContext';

const StatsPanel = ({ itemCount }) => {
  const { widgetRefreshCounter, pageLoads } = useApp();

  return (
    <div className="stats">
      <span>Total Items: <span id="item-count">{itemCount}</span></span>
      <span>Widgets Active: 25</span>
      <span>Widget Refreshes: <span id="widget-refresh-count">{widgetRefreshCounter}</span></span>
      <span>Page Loads: <span id="page-count">{pageLoads}</span></span>
    </div>
  );
};

export default StatsPanel;

// apps/vue/src/components/StatsPanel.vue
<template>
  <div class="stats">
    <span>Total Items: <span id="item-count">{{ itemCount }}</span></span>
    <span>Widgets Active: 25</span>
    <span>Widget Refreshes: <span id="widget-refresh-count">{{ store.widgetRefreshCounter }}</span></span>
    <span>Page Loads: <span id="page-count">{{ store.pageLoads }}</span></span>
  </div>
</template>

<script>
import { store } from '../store'

export default {
  name: 'StatsPanel',
  props: {
    itemCount: {
      type: Number,
      default: 0
    }
  },
  setup() {
    return {
      store
    }
  }
}
</script>
