// apps/react/src/components/Navigation.jsx
import { Link, useLocation } from 'react-router-dom';

const Navigation = () => {
  const location = useLocation();

  return (
    <nav>
      <Link to="/" className={location.pathname === '/' ? 'active' : ''}>
        Home
      </Link>
      <Link to="/about" className={location.pathname === '/about' ? 'active' : ''}>
        About
      </Link>
      <Link to="/contact" className={location.pathname === '/contact' ? 'active' : ''}>
        Contact
      </Link>
    </nav>
  );
};

export default Navigation;

// apps/svelte/src/lib/components/Navigation.svelte
<script>
  import { page } from '$app/stores';
</script>

<nav>
  <a href="/" class:active={$page.url.pathname === '/'}>Home</a>
  <a href="/about" class:active={$page.url.pathname === '/about'}>About</a>
  <a href="/contact" class:active={$page.url.pathname === '/contact'}>Contact</a>
</nav>

<style>
  .active {
    background-color: #555;
  }
</style>
