// apps/angular/src/app/components/placeholder-widget/placeholder-widget.component.ts
import { Component, Input, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { AppService } from '../../app.service';

@Component({
  selector: 'app-placeholder-widget',
  templateUrl: './placeholder-widget.component.html',
  styleUrls: ['./placeholder-widget.component.css']
})
export class PlaceholderWidgetComponent implements OnInit, OnDestroy {
  @Input() id!: number;
  number = 0;
  color = '';
  private subscription?: Subscription;
  private colors = ['#ff6b6b', '#4ecdc4', '#45b7d1', '#f9ca24', '#f0932b', '#eb4d4b', '#6c5ce7', '#a29bfe'];

  constructor(private appService: AppService) {}

  ngOnInit(): void {
    this.color = this.colors[this.id % this.colors.length];
    this.updateNumber();

    this.subscription = this.appService.widgetRefreshCounter$.subscribe(() => {
      this.updateNumber();
    });
  }

  ngOnDestroy(): void {
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
  }

  updateNumber(): void {
    this.number = Math.floor(Math.random() * 1000);
  }
}

<div class="widget" [attr.data-id]="id" [style.border-top]="'4px solid ' + color">
  <h3>Widget {{ id }}</h3>
  <div [style.font-size]="'32px'" [style.font-weight]="'bold'" [style.color]="color">
    {{ number }}
  </div>
</div>

// apps/svelte/src/lib/components/PlaceholderWidget.svelte
<script>
  import { onMount } from 'svelte';
  import { widgetRefreshCounter } from '../stores/appStore.js';
  
  export let id;
  
  const colors = ['#ff6b6b', '#4ecdc4', '#45b7d1', '#f9ca24', '#f0932b', '#eb4d4b', '#6c5ce7', '#a29bfe'];
  const color = colors[id % colors.length];
  
  let number = Math.floor(Math.random() * 1000);
  
  function updateNumber() {
    number = Math.floor(Math.random() * 1000);
  }
  
  $: $widgetRefreshCounter, updateNumber();
</script>

<div class="widget" data-id={id} style="border-top: 4px solid {color}">
  <h3>Widget {id}</h3>
  <div style="font-size: 32px; font-weight: bold; color: {color}">
    {number}
  </div>
</div>
