// apps/angular/src/app/components/stats-panel/stats-panel.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { AppService } from '../../app.service';

@Component({
  selector: 'app-stats-panel',
  templateUrl: './stats-panel.component.html',
  styleUrls: ['./stats-panel.component.css']
})
export class StatsPanelComponent implements OnInit {
  @Input() itemCount = 0;
  widgetRefreshCounter$!: Observable<number>;
  pageLoads$!: Observable<number>;

  constructor(private appService: AppService) {}

  ngOnInit(): void {
    this.widgetRefreshCounter$ = this.appService.widgetRefreshCounter$;
    this.pageLoads$ = this.appService.pageLoads$;
  }
}

<div class="stats">
  <span>Total Items: <span id="item-count">{{ itemCount }}</span></span>
  <span>Widgets Active: 25</span>
  <span>Widget Refreshes: <span id="widget-refresh-count">{{ (widgetRefreshCounter$ | async) || 0 }}</span></span>
  <span>Page Loads: <span id="page-count">{{ (pageLoads$ | async) || 0 }}</span></span>
</div>

// apps/svelte/src/lib/components/StatsPanel.svelte
<script>
  import { widgetRefreshCounter, pageLoads } from '../stores/appStore.js';
  
  export let itemCount = 0;
</script>

<div class="stats">
  <span>Total Items: <span id="item-count">{itemCount}</span></span>
  <span>Widgets Active: 25</span>
  <span>Widget Refreshes: <span id="widget-refresh-count">{$widgetRefreshCounter}</span></span>
  <span>Page Loads: <span id="page-count">{$pageLoads}</span></span>
</div>
