// apps/react/src/pages/Dashboard.jsx
import { useState, useEffect } from 'react';
import { useApp } from '../context/AppContext';
import StatsPanel from '../components/StatsPanel';
import ItemList from '../components/ItemList';
import WeatherWidget from '../components/WeatherWidget';
import PlaceholderWidget from '../components/PlaceholderWidget';

const Dashboard = () => {
  const { incrementItemCounter, decrementItemCounter, refreshWidgets, incrementPageLoads } = useApp();
  const [items, setItems] = useState([]);

  useEffect(() => {
    incrementPageLoads();
  }, []);

  const handleAddItems = (amount) => {
    const newItems = Array.from({ length: amount }, (_, i) => ({
      id: Date.now() + i,
      name: `Item ${items.length + i + 1}`
    }));
    setItems(prev => [...prev, ...newItems]);
    incrementItemCounter(amount);
  };

  const handleRemoveItems = (amount) => {
    setItems(prev => {
      const removed = prev.slice(0, amount);
      const remaining = prev.slice(amount);
      decrementItemCounter(removed.length);
      return remaining;
    });
  };

  const handleRefreshWidgets = () => {
    refreshWidgets();
  };

  return (
    <div className="page">
      <StatsPanel itemCount={items.length} />
      
      <div className="controls">
        <button id="refresh-widgets" onClick={handleRefreshWidgets}>
          Refresh Widgets
        </button>
      </div>

      <div className="dashboard" id="widget-grid">
        <WeatherWidget />
        {Array.from({ length: 24 }, (_, i) => (
          <PlaceholderWidget key={i + 2} id={i + 2} />
        ))}
      </div>

      <ItemList items={items} onAddItems={handleAddItems} onRemoveItems={handleRemoveItems} />
    </div>
  );
};

export default Dashboard;

// apps/vue/src/views/Dashboard.vue
<template>
  <div class="page">
    <StatsPanel :item-count="items.length" />
    
    <div class="controls">
      <button id="refresh-widgets" @click="handleRefreshWidgets">
        Refresh Widgets
      </button>
    </div>

    <div class="dashboard" id="widget-grid">
      <WeatherWidget />
      <PlaceholderWidget 
        v-for="i in 24" 
        :key="i + 1" 
        :id="i + 1" 
      />
    </div>

    <ItemList 
      :items="items" 
      @add-items="handleAddItems"
      @remove-items="handleRemoveItems"
    />
  </div>
</template>

<script>
import { ref, onMounted } from 'vue'
import { store } from '../store'
import StatsPanel from '../components/StatsPanel.vue'
import ItemList from '../components/ItemList.vue'
import WeatherWidget from '../components/WeatherWidget.vue'
import PlaceholderWidget from '../components/PlaceholderWidget.vue'

export default {
  name: 'Dashboard',
  components: {
    StatsPanel,
    ItemList,
    WeatherWidget,
    PlaceholderWidget
  },
  setup() {
    const items = ref([])

    onMounted(() => {
      store.incrementPageLoads()
    })

    const handleAddItems = (amount) => {
      const newItems = Array.from({ length: amount }, (_, i) => ({
        id: Date.now() + i,
        name: `Item ${items.value.length + i + 1}`
      }))
      items.value.push(...newItems)
      store.incrementItemCounter(amount)
    }

    const handleRemoveItems = (amount) => {
      const removed = items.value.splice(0, amount)
      store.decrementItemCounter(removed.length)
    }

    const handleRefreshWidgets = () => {
      store.refreshWidgets()
    }

    return {
      items,
      handleAddItems,
      handleRemoveItems,
      handleRefreshWidgets
    }
  }
}
</script>
